services:
  # Настройки PHP для разработки (монтирование кода)
  laravel-php-httpd-socket:
    volumes:
      - .:/var/www/laravel
      - unix-socket:/var/run/php

  # Настройки Httpd для разработки
  laravel-httpd-socket:
    ports:
      - "${HTTPD_PORT}:80"
    volumes:
      - .:/var/www/laravel
      - unix-socket:/var/run/php
    depends_on:
      - laravel-node-httpd-socket

  # Node.js для сборки фронтенда и Hot Module Replacement (HMR)
  laravel-node-httpd-socket:
    image: node:24-alpine
    container_name: laravel-node-httpd-socket
    working_dir: /var/www/laravel
    volumes:
      - .:/var/www/laravel
      - node_modules:/var/www/laravel/node_modules
    command: >
      sh -lc '
        # Установка зависимостей, если они отсутствуют
        if [ -f package-lock.json ]; then
          npm ci;
        else
          npm install;
        fi;
      
        # Запуск Vite в режиме разработки
        npm run dev -- --host 0.0.0.0 --port 5173
      '
    ports:
      - "5173:5173"
    networks:
      - laravel-httpd-socket-network

volumes:
  node_modules:
